@hostname = localhost
@port = 3333
@host = {{hostname}}:{{port}}/measurement-units
@contentType = application/json

# Create measurement unit
POST http://{{host}}/create
Content-Type:{{contentType}}

{
    "id": "lb",
    "name": "Foot"
}